### ISSUE TITLE
Task #3: Update dependencies

### ISSUE THREAD

**Issue by manosbatsis** [manosbatsis/restdude#4]
Update bower.json and app/main.js to use the dependencies from [calipso-hub's main.js](https://github.com/abissgr/calipso-hub/blob/master/calipso-hub-webapp/src/main/webapp/js/main.js#L44)

**Comment by nkapetanas** [comment]
Dependencies have been updated. Please check and comment if there is anything else you want to add as a dependency.

**Comment by nkapetanas** [comment]
Dependencies have been further updated from  calipso-hub's main.js . Check out app/main.js and package.js .
